dist: trusty
sudo: required
language: bash
services:
- docker
env:
  global:
  - PATH=$HOME/.local/bin:$PATH
before_install:
- pip install --user awscli
- echo "Testing Docker Hub credentials"
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- echo "Docker Hub credentials are working"
before_script:
- docker build --pull=true --rm=false -t ppavlov/jenkins-master .
- docker run -d -p 8080:8080 -p 50000:50000 ppavlov/jenkins-master; sleep 10
script:
- docker ps -a
- curl --retry 10 --retry-delay 5 -v http://localhost:8080/login
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push ppavlov/jenkins-master; fi
notifications:
  email: true
  slack:
    secure: DPw5GguIGTxmTotTv6CocEFYv1H7aUCtxq3P91I5njDkuqpT6deXCA0p+GJSzfHgaTWQuaq4fUcW+qUXa9NnvRheeKrfPg91XpZKC4G4cq4u8oNc+OSneUI96ELKLxsuDrJ855IZVUI6AXbz2Ixl99CfNYShQA5ihDzU77VpkkKpSWhTAC0TWzCggl9NJzzjUQqq5f4u+b9jEcwfPptxkwUD/bJPb+AXMV8Cmxt04J5HL9VjALNg2GN+n8OZr8b2cwqmmdLRq57i1GZ6nkl6j/N2vA2e189RsY4nktp26cIsKuby5xpFdyhBLob0HXmeZqiUHx6M1QbyT5jtif+md+aPrBi22ZQr0U2wjtz1M1jqrntRib13/rgg08WR4qUQdmT45aetuU/HMVQlkGtPTODOdZgp6jJM+8wmhJzktBxTbkRbXozqNVj/AtJ1baJFXxfkdhWSMmys+MIi/hPa204PNUyPWqBTOSil9R/FWlFhsEvu8t/TQdsOTKzplH3x5xJe4TYZs5jzV9IvEZRDlM904qjACzUiLuPvIBtNAq/k/uiKyBM52yMY/0bQ4GG5pTMY9tDutxWxJAIRjnPlWrfZrd6T21ZPHsVinW3z9Z398q6csZnFgkDurcqzg3qIpjFvK/Y718AY1JKkAJSHqJDLDCX3ArdydmqQt9GAv4I=
