sudo: required

language: bash

services:
  - docker

script:
  - docker build --rm=false -t ppavlov/jenkins-master .
  - docker run -d -p 8080:8080 -p 50000:50000 ppavlov/jenkins-master
  - docker ps -a

notifications:
  email: false

