sudo: required

language: bash

services:
  - docker

script:
  - docker build --rm=false -t ppavlov/jenkins-master .
  - docker run -d -p 8080:8080 -p 50000:50000 ppavlov/jenkins-master
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ppavlov/jenkins-master;
    fi

notifications:
  email: true

