branch-defaults:
  master:
    environment: jenkins
global:
  application_name: jenkins-master
  default_ec2_keyname: pavel_pavlov
  default_platform: 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma)
  default_region: eu-west-1
  profile: eb-cli
  sc: git
